### ISSUE TITLE
是否可以开源可视化场景图的代码

### ISSUE THREAD

**Issue by ZQFive** [HCPLab-SYSU/STKET#1]
作者您好，
请问是否可以开源场景图可视化的代码

**Comment by zx332211** [comment]
现在代码不全是吗？

**Comment by ZQFive** [comment]
全的，可以训练和测试的。只是没有可视化和场景图生成的代码。但是目前不需要这个了，感谢你的回答，我把这个issue done掉吧

**Comment by gudukuaile** [comment]
代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r'))  没有这个json文件，

**Comment by ZQFive** [comment]
> 代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r')) 没有这个json文件，

需要自己生成，有个[countPrior.py](https://github.com/HCPLab-SYSU/STKET/blob/main/countPrior.py)可以用。不过没有README要自己看代码把数据集放好。

**Comment by gudukuaile** [comment]
> > 代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r')) 没有这个json文件，
> 
> 需要自己生成，有个[countPrior.py](https://github.com/HCPLab-SYSU/STKET/blob/main/countPrior.py)可以用。不过没有README要自己看代码把数据集放好。

我刚才直接运行了一下这个文件，生成的文件里面只有一对{}，我下载的action_genome1.0的那个数据集，是哪里还需要设置吗，感谢你

**Comment by zx332211** [comment]
你好，感谢您的来信，我前几天也想跑这个项目，但感觉他好像没有公开完整代码，就没有跑，所以没办法回答您的问题，抱歉


.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HCPLab-SYSU/STKET"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月12日(星期五) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HCPLab-SYSU/STKET] 是否可以开源可视化场景图的代码 (Issue #1)





   
代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r')) 没有这个json文件，
  
需要自己生成，有个countPrior.py可以用。不过没有README要自己看代码把数据集放好。
  
我刚才直接运行了一下这个文件，生成的文件里面只有一对{}，我下载的action_genome1.0的那个数据集，是哪里还需要设置吗，感谢你

**Comment by zx332211** [comment]
readme好像都不完整




.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HCPLab-SYSU/STKET"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月12日(星期五) 下午5:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HCPLab-SYSU/STKET] 是否可以开源可视化场景图的代码 (Issue #1)





  
代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r')) 没有这个json文件，
  
需要自己生成，有个countPrior.py可以用。不过没有README要自己看代码把数据集放好。

**Comment by ZQFive** [comment]
> > > 代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r')) 没有这个json文件，
> > 
> > 
> > 需要自己生成，有个[countPrior.py](https://github.com/HCPLab-SYSU/STKET/blob/main/countPrior.py)可以用。不过没有README要自己看代码把数据集放好。
> 
> 我刚才直接运行了一下这个文件，生成的文件里面只有一对{}，我下载的action_genome1.0的那个数据集，是哪里还需要设置吗，感谢你

![image](https://github.com/HCPLab-SYSU/STKET/assets/58469408/e253d715-df75-4d8e-80f2-12d59eef20fd)
按照这个https://github.com/yrcong/STTran的dataset部分设置的文件目录吗？还要手动指定datapath吧。我的代码是CUDA_VISIBLE_DEVICES=3 python countPrior.py -data_path data/scene_understanding/action_genome/

**Comment by zx332211** [comment]
您收到我前面的回信了吗？我没跑过这个项目，因为感觉它好像不完整


.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HCPLab-SYSU/STKET"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月12日(星期五) 下午5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HCPLab-SYSU/STKET] 是否可以开源可视化场景图的代码 (Issue #1)





    
代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r')) 没有这个json文件，
  
需要自己生成，有个countPrior.py可以用。不过没有README要自己看代码把数据集放好。
  
我刚才直接运行了一下这个文件，生成的文件里面只有一对{}，我下载的action_genome1.0的那个数据集，是哪里还需要设置吗，感谢你
  
image.png (view on web)
 按照这个https://github.com/yrcong/STTran的dataset部分设置的文件目录吗？还要手动指定datapath吧。我的代码是CUDA_VISIBLE_DEVICES=3 python countPrior.py -data_path data/scene_understanding/action_genome/

**Comment by gudukuaile** [comment]
> > > > 代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r')) 没有这个json文件，
> > > 
> > > 
> > > 需要自己生成，有个[countPrior.py](https://github.com/HCPLab-SYSU/STKET/blob/main/countPrior.py)可以用。不过没有README要自己看代码把数据集放好。
> > 
> > 
> > 我刚才直接运行了一下这个文件，生成的文件里面只有一对{}，我下载的action_genome1.0的那个数据集，是哪里还需要设置吗，感谢你
> 
> ![image](https://private-user-images.githubusercontent.com/58469408/321943707-e253d715-df75-4d8e-80f2-12d59eef20fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTczNzgsIm5iZiI6MTcxMjkxNzA3OCwicGF0aCI6Ii81ODQ2OTQwOC8zMjE5NDM3MDctZTI1M2Q3MTUtZGY3NS00ZDhlLTgwZjItMTJkNTllZWYyMGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDlmNmUyMmIyYzRmM2JiNTNhMWZmNDNjYjhkMjY0YThjYzVjNTNiNGYzYzc0MWJhNDBhYzU4ODk5N2U1YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QxY3-jMMmg3LXhIqJtkwUBMygT5n3hdj7NlU68irMxo) 按照这个[https://github.com/yrcong/STTran的dataset部分设置的文件目录吗？还要手动指定datapath吧。我的代码是CUDA_VISIBLE_DEVICES=3](https://github.com/yrcong/STTran%E7%9A%84dataset%E9%83%A8%E5%88%86%E8%AE%BE%E7%BD%AE%E7%9A%84%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95%E5%90%97%EF%BC%9F%E8%BF%98%E8%A6%81%E6%89%8B%E5%8A%A8%E6%8C%87%E5%AE%9Adatapath%E5%90%A7%E3%80%82%E6%88%91%E7%9A%84%E4%BB%A3%E7%A0%81%E6%98%AFCUDA_VISIBLE_DEVICES=3) python countPrior.py -data_path data/scene_understanding/action_genome/

我只下载了https://drive.google.com/drive/folders/1LGGPK_QgGbh9gH9SDFv_9LIhBliZbZys这个里面的数据，frames和videos不知道是什么，从哪里下载

**Comment by ZQFive** [comment]
> > > > > 代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r')) 没有这个json文件，
> > > > 
> > > > 
> > > > 需要自己生成，有个[countPrior.py](https://github.com/HCPLab-SYSU/STKET/blob/main/countPrior.py)可以用。不过没有README要自己看代码把数据集放好。
> > > 
> > > 
> > > 我刚才直接运行了一下这个文件，生成的文件里面只有一对{}，我下载的action_genome1.0的那个数据集，是哪里还需要设置吗，感谢你
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/58469408/321943707-e253d715-df75-4d8e-80f2-12d59eef20fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTczNzgsIm5iZiI6MTcxMjkxNzA3OCwicGF0aCI6Ii81ODQ2OTQwOC8zMjE5NDM3MDctZTI1M2Q3MTUtZGY3NS00ZDhlLTgwZjItMTJkNTllZWYyMGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDlmNmUyMmIyYzRmM2JiNTNhMWZmNDNjYjhkMjY0YThjYzVjNTNiNGYzYzc0MWJhNDBhYzU4ODk5N2U1YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QxY3-jMMmg3LXhIqJtkwUBMygT5n3hdj7NlU68irMxo) 按照这个[https://github.com/yrcong/STTran的dataset部分设置的文件目录吗？还要手动指定datapath吧。我的代码是CUDA_VISIBLE_DEVICES=3](https://github.com/yrcong/STTran%E7%9A%84dataset%E9%83%A8%E5%88%86%E8%AE%BE%E7%BD%AE%E7%9A%84%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95%E5%90%97%EF%BC%9F%E8%BF%98%E8%A6%81%E6%89%8B%E5%8A%A8%E6%8C%87%E5%AE%9Adatapath%E5%90%A7%E3%80%82%E6%88%91%E7%9A%84%E4%BB%A3%E7%A0%81%E6%98%AFCUDA_VISIBLE_DEVICES=3) python countPrior.py -data_path data/scene_understanding/action_genome/
> 
> 我只下载了[https://drive.google.com/drive/folders/1LGGPK_QgGbh9gH9SDFv_9LIhBliZbZys这个里面的数据，frames和videos不知道是什么，从哪里下载](https://drive.google.com/drive/folders/1LGGPK_QgGbh9gH9SDFv_9LIhBliZbZys%E8%BF%99%E4%B8%AA%E9%87%8C%E9%9D%A2%E7%9A%84%E6%95%B0%E6%8D%AE%EF%BC%8Cframes%E5%92%8Cvideos%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%8C%E4%BB%8E%E5%93%AA%E9%87%8C%E4%B8%8B%E8%BD%BD)

这里下载的吧？这个里面也有教程生成frames。https://github.com/JingweiJ/ActionGenome?tab=readme-ov-file

**Comment by Lxy811** [comment]
> > > > > > 代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r')) 没有这个json文件，
> > > > > 
> > > > > 
> > > > > 需要自己生成，有个[countPrior.py](https://github.com/HCPLab-SYSU/STKET/blob/main/countPrior.py)可以用。不过没有README要自己看代码把数据集放好。
> > > > 
> > > > 
> > > > 我刚才直接运行了一下这个文件，生成的文件里面只有一对{}，我下载的action_genome1.0的那个数据集，是哪里还需要设置吗，感谢你
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/58469408/321943707-e253d715-df75-4d8e-80f2-12d59eef20fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTczNzgsIm5iZiI6MTcxMjkxNzA3OCwicGF0aCI6Ii81ODQ2OTQwOC8zMjE5NDM3MDctZTI1M2Q3MTUtZGY3NS00ZDhlLTgwZjItMTJkNTllZWYyMGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDlmNmUyMmIyYzRmM2JiNTNhMWZmNDNjYjhkMjY0YThjYzVjNTNiNGYzYzc0MWJhNDBhYzU4ODk5N2U1YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QxY3-jMMmg3LXhIqJtkwUBMygT5n3hdj7NlU68irMxo) 按照这个[https://github.com/yrcong/STTran的dataset部分设置的文件目录吗？还要手动指定datapath吧。我的代码是CUDA_VISIBLE_DEVICES=3](https://github.com/yrcong/STTran%E7%9A%84dataset%E9%83%A8%E5%88%86%E8%AE%BE%E7%BD%AE%E7%9A%84%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95%E5%90%97%EF%BC%9F%E8%BF%98%E8%A6%81%E6%89%8B%E5%8A%A8%E6%8C%87%E5%AE%9Adatapath%E5%90%A7%E3%80%82%E6%88%91%E7%9A%84%E4%BB%A3%E7%A0%81%E6%98%AFCUDA_VISIBLE_DEVICES=3) python countPrior.py -data_path data/scene_understanding/action_genome/
> > 
> > 
> > 我只下载了[https://drive.google.com/drive/folders/1LGGPK_QgGbh9gH9SDFv_9LIhBliZbZys这个里面的数据，frames和videos不知道是什么，从哪里下载](https://drive.google.com/drive/folders/1LGGPK_QgGbh9gH9SDFv_9LIhBliZbZys%E8%BF%99%E4%B8%AA%E9%87%8C%E9%9D%A2%E7%9A%84%E6%95%B0%E6%8D%AE%EF%BC%8Cframes%E5%92%8Cvideos%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%8C%E4%BB%8E%E5%93%AA%E9%87%8C%E4%B8%8B%E8%BD%BD)
> 
> 这里下载的吧？这个里面也有教程生成frames。https://github.com/JingweiJ/ActionGenome?tab=readme-ov-file

你好，这个模型跑起来费GPU吗，需要什么样的配置？

**Comment by ZQFive** [comment]
> > > > > > > 代码有问题，trainPrior = json.load(open('data/TrainPrior.json', 'r')) 没有这个json文件，
> > > > > > 
> > > > > > 
> > > > > > 需要自己生成，有个[countPrior.py](https://github.com/HCPLab-SYSU/STKET/blob/main/countPrior.py)可以用。不过没有README要自己看代码把数据集放好。
> > > > > 
> > > > > 
> > > > > 我刚才直接运行了一下这个文件，生成的文件里面只有一对{}，我下载的action_genome1.0的那个数据集，是哪里还需要设置吗，感谢你
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/58469408/321943707-e253d715-df75-4d8e-80f2-12d59eef20fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTczNzgsIm5iZiI6MTcxMjkxNzA3OCwicGF0aCI6Ii81ODQ2OTQwOC8zMjE5NDM3MDctZTI1M2Q3MTUtZGY3NS00ZDhlLTgwZjItMTJkNTllZWYyMGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDlmNmUyMmIyYzRmM2JiNTNhMWZmNDNjYjhkMjY0YThjYzVjNTNiNGYzYzc0MWJhNDBhYzU4ODk5N2U1YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QxY3-jMMmg3LXhIqJtkwUBMygT5n3hdj7NlU68irMxo) 按照这个[https://github.com/yrcong/STTran的dataset部分设置的文件目录吗？还要手动指定datapath吧。我的代码是CUDA_VISIBLE_DEVICES=3](https://github.com/yrcong/STTran%E7%9A%84dataset%E9%83%A8%E5%88%86%E8%AE%BE%E7%BD%AE%E7%9A%84%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95%E5%90%97%EF%BC%9F%E8%BF%98%E8%A6%81%E6%89%8B%E5%8A%A8%E6%8C%87%E5%AE%9Adatapath%E5%90%A7%E3%80%82%E6%88%91%E7%9A%84%E4%BB%A3%E7%A0%81%E6%98%AFCUDA_VISIBLE_DEVICES=3) python countPrior.py -data_path data/scene_understanding/action_genome/
> > > 
> > > 
> > > 我只下载了[https://drive.google.com/drive/folders/1LGGPK_QgGbh9gH9SDFv_9LIhBliZbZys这个里面的数据，frames和videos不知道是什么，从哪里下载](https://drive.google.com/drive/folders/1LGGPK_QgGbh9gH9SDFv_9LIhBliZbZys%E8%BF%99%E4%B8%AA%E9%87%8C%E9%9D%A2%E7%9A%84%E6%95%B0%E6%8D%AE%EF%BC%8Cframes%E5%92%8Cvideos%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%8C%E4%BB%8E%E5%93%AA%E9%87%8C%E4%B8%8B%E8%BD%BD)
> > 
> > 
> > 这里下载的吧？这个里面也有教程生成frames。https://github.com/JingweiJ/ActionGenome?tab=readme-ov-file
> 
> 你好，这个模型跑起来费GPU吗，需要什么样的配置？

忘记了，可能是3090？显存小的话应该batch_size设置少一点就能跑起来？

**Comment by ParthaNanjanagud** [comment]
> > > There is a problem with the code. trainPrior = json.load(open('data/TrainPrior.json', 'r')) does not have this json file.
> > 
> > 
> > You need to generate it yourself, there is a [countPrior.py](https://github.com/HCPLab-SYSU/STKET/blob/main/countPrior.py) that can be used. However, there is no README, so you need to read the code and put the dataset in place.
> 
> I just ran this file directly, and the generated file contains only a pair of {}. Is there any other setting for the action_genome1.0 dataset I downloaded? Thank you.

Hey, 

Were you able to solve the issue with generating the TestPrior.json file ?

**Comment by zx332211** [comment]
.
***@***.***



&nbsp;很抱歉，我也不太清楚，我当时并没有去跑过这个项目，看到别人说这个代码不全，就想让他公布完整代码再跑，但作者一直未回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HCPLab-SYSU/STKET"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月10日(星期四) 凌晨2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HCPLab-SYSU/STKET] 是否可以开源可视化场景图的代码 (Issue #1)





    
There is a problem with the code. trainPrior = json.load(open('data/TrainPrior.json', 'r')) does not have this json file.
  
You need to generate it yourself, there is a countPrior.py that can be used. However, there is no README, so you need to read the code and put the dataset in place.
  
I just ran this file directly, and the generated file contains only a pair of {}. Is there any other setting for the action_genome1.0 dataset I downloaded? Thank you.
  
Hey,
 
Were you able to solve the issue with generating the TestPrior.json file ?

**Comment by ParthaNanjanagud** [comment]
Oh ok ! thats sad, i am trying to run the code, I will let you know if I was able to solve it.

**Comment by Lxy811** [comment]
> 全的，可以训练和测试的。只是没有可视化和场景图生成的代码。但是目前不需要这个了，感谢你的回答，我把这个issue done掉吧

你好，请问你怎么解决生成空{}的问题的

**Comment by ZQFive** [comment]
> > 全的，可以训练和测试的。只是没有可视化和场景图生成的代码。但是目前不需要这个了，感谢你的回答，我把这个issue done掉吧
> 
> 你好，请问你怎么解决生成空{}的问题的

时间有点久，已经不太清楚了。可以参考一下之前的回答，好像首先要按照这个仓库：https://github.com/yrcong/STTran 
（1）关于数据集设置的文件目录
（2）运行代码时用parser指定datapath。

CUDA_VISIBLE_DEVICES=3 python countPrior.py -data_path data/scene_understanding/action_genome/

**Comment by Lxy811** [comment]
> > > 全的，可以训练和测试的。只是没有可视化和场景图生成的代码。但是目前不需要这个了，感谢你的回答，我把这个issue done掉吧
> > 
> > 
> > 你好，请问你怎么解决生成空{}的问题的
> 
> 时间有点久，已经不太清楚了。可以参考一下之前的回答，好像首先要按照这个仓库：https://github.com/yrcong/STTran （1）关于数据集设置的文件目录 （2）运行代码时用parser指定datapath。
> 
> CUDA_VISIBLE_DEVICES=3 python countPrior.py -data_path data/scene_understanding/action_genome/

好的好的，非常感谢

**Comment by Lxy811** [comment]
> CUDA_VISIBLE_DEVICES=3 python countPrior.py -data_path data/scene_understanding/action_genome/
再次打扰。请问你还有对应生成的json文件吗

**Comment by Lxy811** [comment]
> > > 全的，可以训练和测试的。只是没有可视化和场景图生成的代码。但是目前不需要这个了，感谢你的回答，我把这个issue done掉吧
> > 
> > 
> > 你好，请问你怎么解决生成空{}的问题的
> 
> 时间有点久，已经不太清楚了。可以参考一下之前的回答，好像首先要按照这个仓库：https://github.com/yrcong/STTran （1）关于数据集设置的文件目录 （2）运行代码时用parser指定datapath。
> 
> CUDA_VISIBLE_DEVICES=3 python countPrior.py -data_path data/scene_understanding/action_genome/

不好意思，再次打扰一下，请问你还保留相应的json文件吗

**Comment by ZQFive** [comment]
> > > > 全的，可以训练和测试的。只是没有可视化和场景图生成的代码。但是目前不需要这个了，感谢你的回答，我把这个issue done掉吧
> > > 
> > > 
> > > 你好，请问你怎么解决生成空{}的问题的
> > 
> > 
> > 时间有点久，已经不太清楚了。可以参考一下之前的回答，好像首先要按照这个仓库：https://github.com/yrcong/STTran （1）关于数据集设置的文件目录 （2）运行代码时用parser指定datapath。
> > CUDA_VISIBLE_DEVICES=3 python countPrior.py -data_path data/scene_understanding/action_genome/
> 
> 不好意思，再次打扰一下，请问你还保留相应的json文件吗

不好意思，这个模型我最后并没有用上，所以把占用空间比较大的数据集连同这个导出的结果一并删除了。

**Comment by Lxy811** [comment]
> > > > > 全的，可以训练和测试的。只是没有可视化和场景图生成的代码。但是目前不需要这个了，感谢你的回答，我把这个issue done掉吧
> > > > 
> > > > 
> > > > 你好，请问你怎么解决生成空{}的问题的
> > > 
> > > 
> > > 时间有点久，已经不太清楚了。可以参考一下之前的回答，好像首先要按照这个仓库：https://github.com/yrcong/STTran （1）关于数据集设置的文件目录 （2）运行代码时用parser指定datapath。
> > > CUDA_VISIBLE_DEVICES=3 python countPrior.py -data_path data/scene_understanding/action_genome/
> > 
> > 
> > 不好意思，再次打扰一下，请问你还保留相应的json文件吗
> 
> 不好意思，这个模型我最后并没有用上，所以把占用空间比较大的数据集连同这个导出的结果一并删除了。
好的，感谢你的回复。

**Comment by Lxy811** [comment]
解决了{}的问题，因为运行失败，导致data/TrainAnnos 或 data/TestAnnos 目录为空，进而在 countPrior 函数中的 for annoName in os.listdir(annoPath) 循环无法运行，因为 os.listdir(annoPath) 返回空列表。直接删掉空文件夹，重新运行就行。指令：CUDA_VISIBLE_DEVICES=1 python countPrior.py -data_path /media/dataset/ag/
